export const PLUGIN_FIELD_LABELS: Record<string, string> = {
  plugins: "Plugins",
  "plugins.enabled": "Enable Plugins",
  "plugins.allow": "Plugin Allowlist",
  "plugins.deny": "Plugin Denylist",
  "plugins.load": "Plugin Loader",
  "plugins.load.paths": "Plugin Load Paths",
  "plugins.slots": "Plugin Slots",
  "plugins.slots.memory": "Memory Plugin",
  "plugins.slots.supervisorGuidance": "Supervisor Guidance Plugin",
  "plugins.slots.contextEngine": "Context Engine Plugin",
  "plugins.entries": "Plugin Entries",
  "plugins.entries.*.enabled": "Plugin Enabled",
  "plugins.entries.*.hooks": "Plugin Hook Policy",
  "plugins.entries.*.hooks.allowConversationAccess": "Allow Conversation Access Hooks",
  "plugins.entries.*.hooks.allowPromptInjection": "Allow Prompt Injection Hooks",
  "plugins.entries.*.hooks.timeoutMs": "Plugin Hook Timeout (ms)",
  "plugins.entries.*.hooks.timeouts": "Plugin Hook Timeout Overrides",
  "plugins.entries.*.subagent": "Plugin Subagent Policy",
  "plugins.entries.*.subagent.allowModelOverride": "Allow Plugin Subagent Model Override",
  "plugins.entries.*.subagent.allowedModels": "Plugin Subagent Allowed Models",
  "plugins.entries.*.llm": "Plugin LLM Policy",
  "plugins.entries.*.llm.allowModelOverride": "Allow Plugin LLM Model Override",
  "plugins.entries.*.llm.allowedModels": "Plugin LLM Allowed Models",
  "plugins.entries.*.llm.allowedCompletionModels": "Plugin LLM Allowed Completion Models",
  "plugins.entries.*.llm.allowAuthProfileOverride": "Allow Plugin LLM Auth Profile Override",
  "plugins.entries.*.llm.allowAgentIdOverride": "Allow Plugin LLM Agent Override",
  "plugins.entries.*.apiKey": "Plugin API Key", // pragma: allowlist secret
  "plugins.entries.*.env": "Plugin Environment Variables",
  "plugins.entries.*.config": "Plugin Config",
};
